### ISSUE TITLE
Support Editing Mirrors

### ISSUE THREAD

**Issue by nhandler** [alphagov/puppet-aptly#39]
Currently, puppet-aptly checks if a mirror by the same name already exists. If it does, no action is taken. This has the side effect of not allowing edits to be made to an already created mirror. Since aptly has an `aptly mirror edit` feature, puppet-aptly should look into adding support for this.

**Comment by surminus** [comment]
Hi,

Sorry for the (very) slow reply! I am looking into how we might be able to implement this. The current workaround would be to create mirrors with unique names. I'm assuming you'd like to be able to update the location/architecture/keys etc of a mirror without renaming or removing the mirror?

**Comment by sengi** [comment]
Hi there, @nhandler. Apologies for the thread necromancy — I'm closing this out so you don't get stuck with an unresolvable issue when this repo is archived.

We don't have anyone maintaining this repo any more as we no longer run Puppet. I'm about to archive this and a bunch of other Puppet-related repos that we haven't touched in a long time.

Thanks for taking the time to report this issue ❤️
