### ISSUE TITLE
Feature request: publish support

### ISSUE THREAD

**Issue by kali-brandwatch** [alphagov/puppet-aptly#66]
As far as I could understand from using the module and reading the code, there is no support for publishing right now.

I am using this module to create a debian reporsitory from puppet, and i would like puppet to be able to not only create the repository and mirrors, but also manage publishing them.

Right now all of those are done from my wrapper class which calls this module, but in a rather ugly way.

Is there any planned support for publishing repos/snapshots in a near future?

Thanks

**Comment by sengi** [comment]
Hi there, @kali-brandwatch. Apologies for the thread necromancy — I'm closing this out so you don't get stuck with an unresolvable issue when this repo is archived.

We don't have anyone maintaining this repo any more as we no longer run Puppet. I'm about to archive this and a bunch of other Puppet-related repos that we haven't touched in a long time.

Thanks for taking the time to report this issue ❤️
