### ISSUE TITLE
Lastest versions of stdlib and apt modules are not supported

### ISSUE THREAD

**Issue by jormaster3k** [alphagov/puppet-aptly#89]
Hi,

The latest version (1.0.0) is not compatible with the latest versions of stdlib and apt.

This module requires a version below 5.0.0 for both stdlib and apt, which have a latest version of 6.0.0 and 7.0.1 respectively.

Thanks,
Jory

**Comment by sid3windr** [comment]
Any news here? I forced an install and things work, but it's a bit ugly right now. :-)

**Comment by sengi** [comment]
Hi there @jormaster3k and @sid3windr! Sorry to be the bearer of bad news, but unfortunately we don't actually have anyone maintaining this repo any more as we no longer run Puppet. I'm about to archive this and a bunch of other Puppet-related repos that we haven't touched in a long time.

My apologies that we haven't signposted that we're no longer set up to receive outside contributions in this repo until now.

You're most welcome to fork, of course — not that that's much consolation. Thanks for taking the time to report this issue ❤️
