### ISSUE TITLE
[Feature Request] Add Ubuntu 20.04 support

### ISSUE THREAD

**Issue by QueerCodingGirl** [alphagov/puppet-aptly#96]
Right now there are only old versions of ubuntu present in the metadata.json.
Does this module work with Ubuntu 20.04? If so, could you add that to the metadata, please?

**Comment by sengi** [comment]
We're about to archive this repo unfortunately.

Here at GOV.UK we've only ever used this with Ubuntu 14.04(!) so YMMV. Appreciate you taking the time to raise the issue and sorry I can't help on this occasion.
