### ISSUE TITLE
[Feature Request] Add Puppet 7 support

### ISSUE THREAD

**Issue by QueerCodingGirl** [alphagov/puppet-aptly#97]
Does this module work with Puppet 7? Could you add the version 7 as a supported version, please?

**Comment by sengi** [comment]
Hi there, @QueerCodingGirl! Sorry to be the bearer of bad news, but unfortunately we don't actually have anyone maintaining this repo any more as we no longer run Puppet. I'm about to archive this and a bunch of other Puppet-related repos that we haven't touched in a long time.

My apologies that we haven't signposted that we're no longer set up to receive outside contributions in this repo until now.

You're most welcome to fork, of course — not that that's much consolation. Thanks for taking the time to report this issue ❤️
